---
title: "boston"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{boston}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
#remotes::install_github("PengSU517/robcovsel")
#remotes::install_github("PengSU517/shootings") !!!!!!!!!!!!!!
#This shootings package is not my original work. The functions in this package were forked from https://github.com/ineswilms/sparse-shooting-S. I constructed a package of those functions to make them more convenient to use.
library(MASS) # the Boston dataset
library(robcovsel)
library(tidyverse)
library(doParallel)
registerDoParallel(cores=10)
```


```{r settings}
{
  data("Boston")
  y = log(Boston$medv)
  Boston = Boston %>% mutate(loglstat = log(lstat), logdis = log(dis), logcrim = log(crim))
  predictors = Boston[, c("loglstat", "rm", "logdis", "tax", "ptratio","nox", "age", "black", "logcrim")]
}


{
  ms = 1:10
  es = c(0, 0.1)
}
```

```{r empirical work}
system.time({result = foreach(m = 1:1000, .combine = "rbind", 
                              .packages = c("shootings", "robustHD", "robcovsel"))%:%
  
  foreach(e = es, .combine = "rbind")%dopar%
  {
    {
      set.seed(m)
      n = length(y)
      pr = 10
      r = 0.5
      mur = rep(0,pr)
      sigmar = diag(rep(1^2,pr))
      for (i in 1:pr) {for (j in 1:pr) {
        if (i !=j)sigmar[i,j] = sqrt(sigmar[i,i]*sigmar[j,j])*r^abs(i-j)}}
      xr = MASS::mvrnorm(n,mur,sigmar)
      x = robustHD::robStandardize(cbind(predictors, xr), centerFun = median,  scaleFun = robustbase::Qn)
      p = dim(x)[2]
      
      gamma = 10
      mu = rep(0,p)
      sigma = covf(x,cor.method = "pearson", scale.method = "qn", pda.method = F)$covmatrix
      
      bi = apply(matrix(0, nrow = n, ncol = p), 2, 
                 function(xvec) {xvec[sample(x = 1:n, size = e*n)] = 1; return(xvec)})
      outlier = matrix(rnorm(n = n*p, mean = gamma, sd = 1),nrow = n,ncol=p)
      xx = x*(1-bi) + bi*outlier
      yy = y
    }

    {
      lassofit = covlasso(xx,yy,cor.method = "pearson", scale.method = "sd", pda.method = F, adaptive = F)$betahat_opt
      sLTSfit = sparseLTS(xx,yy)$coefficients[-1]
      sssfit = sparseshooting(xx,yy)$coef[-1]
      pairfit = covlasso(xx,yy)$betahat_opt
      gaussrankfit = covlasso(xx,yy,cor.method = "gaussrank")$betahat_opt
      
      rst = rbind(e = e, m = m, cbind(lassofit, sLTSfit,sssfit, pairfit, gaussrankfit))
      colnames(rst) = c("lasso", "sLTS", "sShootingS", "ALRP","ALGR")
    }
    
    t(rst)
  }})

```

```{r analysis}
{
  Boston_result = as.data.frame(as.matrix(result))
  Boston_result$method = rownames(result)
  #save(Boston_result, file = "Boston_result.Rdata")
  Boston_result$method = factor(Boston_result$method, levels = c("lasso", "sLTS", "sShootingS", "ALGR", "ALRP"))
  table = aggregate(.~e + method, data = Boston_result, function(x)mean(as.logical(x)))
  tbl = cbind(table[,(1:11)],redundant = rowMeans(table[,-(1:11)]));
  colnames(tbl)[3:11] = c("loglstat", "rm", "logdis", "tax", "ptratio", "nox", "age", "black", "logcrim")
  #write_csv(tbl, "Boston_table.csv")
}


tbl
```





